[profile.default]
src = "contracts/src"
test = "contracts/test"
script = "contracts/script"
out = "contracts/out"
cache_path = "contracts/cache"
libs = ["node_modules", "contracts/lib"]
ignored_error_codes = [
    #"license",
    #"code-size",
    #"init-code-size",
]
deny_warnings = true
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "ds-test/=contracts/lib/forge-std/lib/ds-test/src/",
    "forge-std/=contracts/lib/forge-std/src/",
]
fs_permissions = [{ access = "read", path = "./contracts/out"}]
solc_version = "0.8.28"
# LINEA: keep solc version low
#solc_version = "0.8.20"
#evm_version = 'paris'
# ROOTSTOCK: is on london (prevrandao error)
#evm_version = 'london'
# MANTLE: is on london (prevrandao error)
#evm_version = 'paris'
# SAGA: idk tbh
#evm_version = 'shanghai'
# HYPEREVM: is on paris (prevrandao error)
evm_version = 'cancun'

[profile.gas-optimize]
optimizer = true
optimizer_runs = 200_000_000
via_ir = true

[profile.gas-optimize.optimizer_details]
inliner = true
deduplicate = true
constantOptimizer = true
# yul = true # makes it worse
# orderLiterals = true # makes it worse
# cse = true # makes it worse