{
 "title": "Context Data (vaults & chain config)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chains",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 0 },
   "targets": [
    { "rawSql": "select * FROM chain " }
   ]
  },
  {
   "title": "Strats counts",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT chain, count(*)\nFROM vault\ngroup by 1"
    }
   ]
  },
  {
   "title": "All vaults",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT id, eol, chain, bytea_to_hexstr(strategy_address) as strategy_address, platform_id, tvl_usd \nFROM vault"
    }
   ]
  }
 ]
}