{
 "title": "Cowllector Wallet Balances",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select c.chain from chain c where not c.eol"
   }
  ]
 },
 "panels": [
  {
   "title": "Native Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  chain,\n  date_trunc('hour', datetime) as time,\n  eth_wei_to_eth(min(balance_before_native_wei)) as balance_before_native,\n  eth_wei_to_eth(min(balance_after_native_wei))  as balance_after_native\nFROM\n  cowllector_run \nWHERE chain IN ( $chain )\nGROUP BY 1,2, datetime\nORDER BY\n  datetime"
    }
   ]
  },
  {
   "title": "WNative Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  chain,\n  date_trunc('hour', datetime) as time,\n  eth_wei_to_eth(min(balance_before_wnative_wei)) as balance_before_wnative,\n  eth_wei_to_eth(min(balance_after_wnative_wei)) as balance_after_wnative\nFROM\n  cowllector_run \nWHERE chain IN ( $chain )\nGROUP BY 1,2, datetime\nORDER BY\n  datetime"
    }
   ]
  },
  {
   "title": "Native+WNative Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  chain,\n  date_trunc('hour', datetime) as time,\n  eth_wei_to_eth(min(balance_before_aggregated_wei)) as balance_before_total,\n  eth_wei_to_eth(min(balance_after_aggregated_wei)) as balance_after_total\nFROM\n  cowllector_run \nWHERE chain IN ( $chain )\nGROUP BY 1,2, datetime\nORDER BY\n  datetime"
    }
   ]
  }
 ]
}