{
 "title": "Cowllector Wallet Balances Overview",
 "time": { "from": "now-5d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select c.chain from chain c where not c.eol"
   }
  ]
 },
 "panels": [
  {
   "title": "Native+WNative Balance Change from first shown point (%)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    first_value(eth_wei_to_eth(min(balance_before_aggregated_wei))) over (w) as first_balance_before,\n    first_value(eth_wei_to_eth(min(balance_after_aggregated_wei))) over (w) as first_balance_after,\n    eth_wei_to_eth(min(balance_before_aggregated_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_aggregated_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ($chain) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n  window w as (partition by chain order by datetime)\n  ORDER BY\n    datetime\n)\nselect \n  chain,\n  datetime as time,\n  case when first_balance_before = 0 then 0 else\n  (balance_before_total - first_balance_before) / first_balance_before\n  end as percent_change_from_balance_before--,\n  --(balance_after_total - first_balance_after) / first_balance_after as percent_change_from_balance_after\nfrom ts"
    }
   ]
  },
  {
   "title": "Native+WNative Balance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "\nwith balance_ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    eth_wei_to_eth(min(balance_before_aggregated_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_aggregated_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ($chain) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n)\nSELECT\n  chain,\n  datetime as time,\n  case when (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) = 0 then 0 else\n  balance_before_total / (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) end as balance_before_percent,\n  case when (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) = 0 then 0 else \n  balance_after_total / (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) end as balance_after_percent\nFROM\n  balance_ts\nORDER BY\n  datetime"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Native Balance Change from first shown point (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    first_value(eth_wei_to_eth(min(balance_before_native_wei))) over (w) as first_balance_before,\n    first_value(eth_wei_to_eth(min(balance_after_native_wei))) over (w) as first_balance_after,\n    eth_wei_to_eth(min(balance_before_native_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_native_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ($chain) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n  window w as (partition by chain order by datetime)\n  ORDER BY\n    datetime\n)\nselect \n  chain,\n  datetime as time,\n  case when first_balance_before = 0 then 0 else\n  (balance_before_total - first_balance_before) / first_balance_before end as percent_change_from_balance_before,\n  case when first_balance_after = 0 then 0 else\n  (balance_after_total - first_balance_after) / first_balance_after end as percent_change_from_balance_after\nfrom ts"
    }
   ]
  },
  {
   "title": "Native Balance from first value (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "\nwith balance_ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    eth_wei_to_eth(min(balance_before_native_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_native_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ($chain) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n)\nSELECT\n  chain,\n  datetime as time,\n  case when (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) = 0 then 0 else\n  balance_before_total / (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) end as balance_before_percent,\n  case when (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) = 0 then 0 else \n  balance_after_total / (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) end as balance_after_percent\nFROM\n  balance_ts\nORDER BY\n  datetime"
    }
   ]
  },
  {
   "title": "WNative Balance Change from first shown point (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    first_value(eth_wei_to_eth(min(balance_before_wnative_wei))) over (w) as first_balance_before,\n    first_value(eth_wei_to_eth(min(balance_after_wnative_wei))) over (w) as first_balance_after,\n    eth_wei_to_eth(min(balance_before_wnative_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_wnative_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ($chain) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n  window w as (partition by chain order by datetime)\n  ORDER BY\n    datetime\n)\nselect \n  chain,\n  datetime as time,\n  case when first_balance_before = 0 then 0 else \n  (balance_before_total - first_balance_before) / first_balance_before end as percent_change_from_balance_before,\n  case when first_balance_after = 0 then 0 else\n  (balance_after_total - first_balance_after) / first_balance_after end as percent_change_from_balance_after\nfrom ts"
    }
   ]
  },
  {
   "title": "WNative Balance from first value (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "\nwith balance_ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    eth_wei_to_eth(min(balance_before_wnative_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_wnative_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ($chain) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n)\nSELECT\n  chain,\n  datetime as time,\n  case when (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) = 0 then 0 else\n  balance_before_total / (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) end as balance_before_percent,\n  case when (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) = 0 then 0 else\n  balance_after_total / (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) end as balance_after_percent\nFROM\n  balance_ts\nORDER BY\n  datetime"
    }
   ]
  }
 ]
}