{
 "title": "Cowllector Wallet Balances",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain",
    "query": "select c.chain from chain c where not c.eol"
   }
  ]
 },
 "panels": [
  {
   "title": "Native+WNative Balance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  chain,\n  date_trunc('hour', datetime) as time,\n  eth_wei_to_eth(min(balance_before_aggregated_wei)) as balance_before_total,\n  eth_wei_to_eth(min(balance_after_aggregated_wei)) as balance_after_total\nFROM\n  cowllector_run \nWHERE chain IN ( '$chain' ) and $__timeFilter(datetime) \nGROUP BY 1,2, datetime\nORDER BY\n  datetime"
    }
   ]
  },
  {
   "title": "Native+WNative Balance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "\nwith balance_ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    eth_wei_to_eth(min(balance_before_aggregated_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_aggregated_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ( '$chain' ) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n)\nSELECT\n  chain,\n  datetime as time,\n  balance_before_total / (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) as balance_before_percent,\n  balance_after_total / (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) as balance_after_percent\nFROM\n  balance_ts\nORDER BY\n  datetime"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Native Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  chain,\n  date_trunc('hour', datetime) as time,\n  eth_wei_to_eth(min(balance_before_native_wei)) as balance_before_native,\n  eth_wei_to_eth(min(balance_after_native_wei))  as balance_after_native\nFROM\n  cowllector_run \nWHERE chain IN ( '$chain' ) and $__timeFilter(datetime) \nGROUP BY 1,2, datetime\nORDER BY\n  datetime"
    }
   ]
  },
  {
   "title": "Native Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "\nwith balance_ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    eth_wei_to_eth(min(balance_before_native_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_native_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ( '$chain' ) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n)\nSELECT\n  chain,\n  datetime as time,\n  balance_before_total / (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) as balance_before_percent,\n  balance_after_total / (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) as balance_after_percent\nFROM\n  balance_ts\nORDER BY\n  datetime"
    }
   ]
  },
  {
   "title": "WNative Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  chain,\n  date_trunc('hour', datetime) as time,\n  eth_wei_to_eth(min(balance_before_wnative_wei)) as balance_before_wnative,\n  eth_wei_to_eth(min(balance_after_wnative_wei)) as balance_after_wnative\nFROM\n  cowllector_run \nWHERE chain IN ( '$chain' ) and $__timeFilter(datetime) \nGROUP BY 1,2, datetime\nORDER BY\n  datetime"
    }
   ]
  },
  {
   "title": "Native Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "\nwith balance_ts as (\n  SELECT\n    chain,\n    date_trunc('hour', datetime) as datetime,\n    eth_wei_to_eth(min(balance_before_wnative_wei)) as balance_before_total,\n    eth_wei_to_eth(min(balance_after_wnative_wei)) as balance_after_total\n  FROM\n    cowllector_run \n  WHERE chain IN ( '$chain' ) and $__timeFilter(datetime) \n  GROUP BY 1,2, datetime\n)\nSELECT\n  chain,\n  datetime as time,\n  balance_before_total / (FIRST_VALUE(balance_before_total) over (partition by chain order by datetime asc)) as balance_before_percent,\n  balance_after_total / (FIRST_VALUE(balance_after_total) over (partition by chain order by datetime asc)) as balance_after_percent\nFROM\n  balance_ts\nORDER BY\n  datetime"
    }
   ]
  }
 ]
}