# config file version
apiVersion: 1

# configure manually and get the json data from /api/datasources

datasources:
  - name: Beefy Cowllector DB
    type: postgres
    access: proxy
    url: ${DATABASE_URL}
    isDefault: true
    jsonData:
      postgresVersion: 1500
      sslmode: "disable"
      timeInterval: "15m"
      timescaledb: false
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: "file-path"
      tlsSkipVerify: true
    editable: false
