# config file version
apiVersion: 1

# configure manually and get the json data from /api/datasources

datasources:
  - name: Beefy Cowllector DB
    type: postgres
    access: proxy
    url: ${PG_HOSTNAME}:${PG_PORT}
    user: ${PG_USERNAME}
    database: ${PG_DATABASE}
    isDefault: true
    jsonData:
      postgresVersion: 1500
      sslmode: "require"
      timeInterval: "15m"
      timescaledb: false
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsConfigurationMethod: "file-path"
      tlsSkipVerify: true
    secureJsonData:
      password: ${PG_PASSWORD}
    editable: false
